image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

build:
  tags:
    - wheels
  stage: build
  script:
    - docker login -u=$QUAY_ROBOT_USERNAME -p=$QUAY_ROBOT_PASSWD quay.io
    - docker run --rm -e WHEELS_DEST='/shared/repository/targets/wheels' -e CORE_GIT_BRANCH='master' -v $PWD/shared:/shared  quay.io/datadog/integrations-core-wheels-builder:latest
    - docker logout quay.io
